In [1]:
import datetime
import time
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('T1.csv')
data.head()

Date/Time  LV ActivePower (kW)  Wind Speed (m/s)  \
0  01 01 2018 00:00           380.047791          5.311336   
1  01 01 2018 00:10           453.769196          5.672167   
2  01 01 2018 00:20           306.376587          5.216037   
3  01 01 2018 00:30           419.645905          5.659674   
4  01 01 2018 00:40           380.650696          5.577941   

   Theoretical_Power_Curve (KWh)  Wind Direction (°)  
0                     416.328908          259.994904  
1                     519.917511          268.641113  
2                     390.900016          272.564789  
3                     516.127569          271.258087  
4                     491.702972          265.674286

In [3]:
data.rename(columns={'Theoretical_Power_Curve (KWh)':'Power','LV ActivePower (kW)':'ActivePower',"Wind Speed (m/s)":"WindSpeed","Wind Direction (°)":"WindDirection"},
                inplace=True)
data.head()

Date/Time  ActivePower  WindSpeed       Power  WindDirection
0  01 01 2018 00:00   380.047791   5.311336  416.328908     259.994904
1  01 01 2018 00:10   453.769196   5.672167  519.917511     268.641113
2  01 01 2018 00:20   306.376587   5.216037  390.900016     272.564789
3  01 01 2018 00:30   419.645905   5.659674  516.127569     271.258087
4  01 01 2018 00:40   380.650696   5.577941  491.702972     265.674286

In [4]:
# seprate the time 
data['Time']=data['Date/Time'].apply(lambda x: time.strptime(x,"%d %m %Y %H:%M")[4])
data.head()

Date/Time  ActivePower  WindSpeed       Power  WindDirection  Time
0  01 01 2018 00:00   380.047791   5.311336  416.328908     259.994904     0
1  01 01 2018 00:10   453.769196   5.672167  519.917511     268.641113    10
2  01 01 2018 00:20   306.376587   5.216037  390.900016     272.564789    20
3  01 01 2018 00:30   419.645905   5.659674  516.127569     271.258087    30
4  01 01 2018 00:40   380.650696   5.577941  491.702972     265.674286    40

In [5]:
temp=data['Time'][1:].values - data['Time'][0:-1].values
temp=np.array([0]+list(temp))

In [6]:
data['TimeDiff']=temp

In [7]:
data.head()

Date/Time  ActivePower  WindSpeed       Power  WindDirection  Time  \
0  01 01 2018 00:00   380.047791   5.311336  416.328908     259.994904     0   
1  01 01 2018 00:10   453.769196   5.672167  519.917511     268.641113    10   
2  01 01 2018 00:20   306.376587   5.216037  390.900016     272.564789    20   
3  01 01 2018 00:30   419.645905   5.659674  516.127569     271.258087    30   
4  01 01 2018 00:40   380.650696   5.577941  491.702972     265.674286    40   

   TimeDiff  
0         0  
1        10  
2        10  
3        10  
4        10

In [8]:
data.tail()

Date/Time  ActivePower  WindSpeed        Power  WindDirection  \
50525  31 12 2018 23:10  2963.980957  11.404030  3397.190793      80.502724   
50526  31 12 2018 23:20  1684.353027   7.332648  1173.055771      84.062599   
50527  31 12 2018 23:30  2201.106934   8.435358  1788.284755      84.742500   
50528  31 12 2018 23:40  2515.694092   9.421366  2418.382503      84.297913   
50529  31 12 2018 23:50  2820.466064   9.979332  2779.184096      82.274620   

       Time  TimeDiff  
50525    10        10  
50526    20        10  
50527    30        10  
50528    40        10  
50529    50        10

In [9]:
data['Gust']=np.array([0]+list(data['WindSpeed'][1:].values-data['WindSpeed'][:-1].values))
data.head()

Date/Time  ActivePower  WindSpeed       Power  WindDirection  Time  \
0  01 01 2018 00:00   380.047791   5.311336  416.328908     259.994904     0   
1  01 01 2018 00:10   453.769196   5.672167  519.917511     268.641113    10   
2  01 01 2018 00:20   306.376587   5.216037  390.900016     272.564789    20   
3  01 01 2018 00:30   419.645905   5.659674  516.127569     271.258087    30   
4  01 01 2018 00:40   380.650696   5.577941  491.702972     265.674286    40   

   TimeDiff      Gust  
0         0  0.000000  
1        10  0.360831  
2        10 -0.456130  
3        10  0.443637  
4        10 -0.081733

In [10]:
data.dtypes

Date/Time         object
ActivePower      float64
WindSpeed        float64
Power            float64
WindDirection    float64
Time               int64
TimeDiff           int64
Gust             float64
dtype: object

In [11]:
data_=data[data['TimeDiff'].isin([10,-50])]
data_.head()

Date/Time  ActivePower  WindSpeed       Power  WindDirection  Time  \
1  01 01 2018 00:10   453.769196   5.672167  519.917511     268.641113    10   
2  01 01 2018 00:20   306.376587   5.216037  390.900016     272.564789    20   
3  01 01 2018 00:30   419.645905   5.659674  516.127569     271.258087    30   
4  01 01 2018 00:40   380.650696   5.577941  491.702972     265.674286    40   
5  01 01 2018 00:50   402.391998   5.604052  499.436385     264.578613    50   

   TimeDiff      Gust  
1        10  0.360831  
2        10 -0.456130  
3        10  0.443637  
4        10 -0.081733  
5        10  0.026111

In [12]:
len(data_)

50500

In [13]:
data_=data_[data_['ActivePower']>=0]
data_.describe()

ActivePower     WindSpeed         Power  WindDirection          Time  \
count  50443.000000  50443.000000  50443.000000   50443.000000  50443.000000   
mean    1309.932554      7.565593   1494.454238     123.716485     24.997125   
std     1312.471586      4.226063   1367.906548      93.425141     17.078962   
min        0.000000      0.000000      0.000000       0.000000      0.000000   
25%       53.512621      4.212597    163.517562      49.344398     10.000000   
50%      828.896973      7.114135   1068.206544      73.689552     20.000000   
75%     2485.947510     10.307985   2969.201056     201.697906     40.000000   
max     3618.732910     25.206011   3600.000000     359.997589     50.000000   

           TimeDiff          Gust  
count  50443.000000  50443.000000  
mean      -0.002181      0.001787  
std       22.362852      0.742791  
min      -50.000000    -14.075440  
25%       10.000000     -0.380538  
50%       10.000000      0.001451  
75%       10.000000      0.379923  
max       10.000000     17.411289

In [14]:
x_train=data_[['WindSpeed','WindDirection','Gust']].values
y_train=data_['ActivePower'].values

In [15]:
!pip install lightgbm

You should consider upgrading via the 'c:\users\hp\anaconda3\python.exe -m pip install --upgrade pip' command.


In [25]:
!pip install catboost

You should consider upgrading via the 'c:\users\hp\anaconda3\python.exe -m pip install --upgrade pip' command.


In [16]:
from sklearn.linear_model import ElasticNet, Lasso,  BayesianRidge, LassoLarsIC
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.neighbors import KNeighborsRegressor,RadiusNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error,r2_score
import xgboost as xgb
import lightgbm as lgb
from catboost import CatBoostRegressor
#from sklearn.experimental import enable_hist_gradient_boosting 
#from sklearn.ensemble import HistGradientBoostingRegressor

C:\Users\HP\Anaconda3\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
C:\Users\HP\Anaconda3\lib\site-packages\distributed\config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
C:\Users\HP\Anaconda3\lib\site-packages\distributed\utils.py:134: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [WinError 10051] A socket operation was attempted to an unreachable network
  % (host, default, e), RuntimeWarning)


In [32]:
!pip install xgboost

You should consider upgrading via the 'c:\users\hp\anaconda3\python.exe -m pip install --upgrade pip' command.


In [17]:
n_folds = 5

def rmsle_cv(model):
    kf = KFold(n_folds, shuffle=True, random_state=15).get_n_splits(data_.values)
    rmse= np.sqrt(-cross_val_score(model, x_train, y_train, scoring="neg_mean_squared_error", cv = kf))
    return(rmse)

In [18]:
lasso = make_pipeline(RobustScaler(), Lasso(alpha = 0.5))
score = rmsle_cv(lasso)
print("\nLasso score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))
score


Lasso score: 532.5939 (166.2872)



array([838.45847838, 438.69383302, 350.88994159, 482.73217465,
       552.19514451])

In [19]:

KNR=KNeighborsRegressor(n_neighbors=8, weights='uniform', algorithm='auto', leaf_size=100, p=1, metric='minkowski')

score = rmsle_cv(KNR)
print("KNR score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))
score

KNR score: 432.0385 (180.3508)



array([717.42917953, 294.25463431, 250.46500532, 329.32630819,
       568.71743596])

In [20]:
model_xgb1 = xgb.XGBRegressor(learning_rate=2e-2, max_depth=4, 
                             min_child_weight=1.1, n_estimators=100,
                             reg_alpha=0.3, reg_lambda=0.7,
                             #subsample=0.5213, silent=1,
                             nthread = -1)

In [21]:
model_xgb1.fit(x_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
       importance_type='gain', interaction_constraints='',
       learning_rate=0.02, max_delta_step=0, max_depth=4,
       min_child_weight=1.1, missing=nan, monotone_constraints='()',
       n_estimators=100, n_jobs=-1, nthread=-1, num_parallel_tree=1,
       objective='reg:squarederror', random_state=0, reg_alpha=0.3,
       reg_lambda=0.7, scale_pos_weight=1, subsample=1,
       tree_method='exact', validate_parameters=1, verbosity=None)

In [22]:
preds=model_xgb1.predict(x_train)
score=mean_squared_error(y_train,preds)
score**0.5

450.24259360681566

In [23]:
r2_score(y_train,preds)

0.882314774332115

In [24]:
model_xgb1.predict(np.array([6.02,110.0,0.23]).reshape(1,-1))

array([454.7521], dtype=float32)

In [25]:
model_lgb1 = lgb.LGBMRegressor(objective='regression',num_leaves=2,
                              learning_rate=0.07, n_estimators=80,
                              #max_bin = 255, bagging_fraction = 0.8,
                              #bagging_freq = 5, feature_fraction = 0.8,
                              #feature_fraction_seed=9, bagging_seed=9,
                              reg_alpha=0.3,reg_lambda=0.7,
                              #min_data_in_leaf =3, min_sum_hessian_in_leaf = 2
                             )

In [26]:
model_lgb1.fit(x_train,y_train)

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
       importance_type='split', learning_rate=0.07, max_depth=-1,
       min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
       n_estimators=80, n_jobs=-1, num_leaves=2, objective='regression',
       random_state=None, reg_alpha=0.3, reg_lambda=0.7, silent=True,
       subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [27]:
preds=model_lgb1.predict(x_train)
score=mean_squared_error(y_train,preds)
score**0.5

391.9123625549006

In [28]:
r2_score(y_train,preds)

0.910832474267455

In [29]:
model_lgb1.predict(np.array([6.02,110.0,0.23]).reshape(1,-1))

array([542.52738079])

# TESTING OF DATA

In [30]:
#CREATING DATA FFOR TESTING

In [31]:
#test=[]
#for i in range(1,6):
#    test.append(pd.read_csv(f'test{i}.csv'))


FileNotFoundError: [Errno 2] File b'test1.csv' does not exist: b'test1.csv'